build:
    environment:
        php:
            version: 5.6.9

    dependencies:
            before:
                - pecl install mongodb
                - echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
                - composer install
                - sudo apt-get install -y mongodb-org
                - mongoimport --db test --collection restaurants --drop --file dump/dataset.json