language: php

php:
  - '5.6'
  - '7.0'

services: mongodb

before_script:
    - pecl install mongodb
    - echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - composer self-update
    - composer install
    - mongoimport --db tests --collection restaurants --drop --file dump/dataset.json

script:
  - phpunit --bootstrap vendor/autoload.php tests