language: php
php:
  - '5.6'
  - '7.0'
before_script:
    - pecl install mongodb
    - echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - composer self-update
    - composer install

script:
  - phpunit --bootstrap vendor/autoload.php test